#!/usr/bin/env php
<?php

/**
 * @package    at.theroadtojoy.secretsanta
 * @author     Florian Eckerstorfer <f.eckerstorfer@gmail.com>
 * @license    http://www.opensource.org/licenses/mit-license.php MIT License
 */

define('BASE_DIR', __DIR__);

// Include Symfony2 ClassLoader & SwiftMailer
require_once BASE_DIR . '/src/vendor/Symfony/Component/ClassLoader/UniversalClassLoader.php';
require_once BASE_DIR . '/src/vendor/swiftmailer/lib/swift_required.php';

use Symfony\Component\ClassLoader\UniversalClassLoader;
use Symfony\Component\Console\Application;

use SecretSanta\Command\SecretSantaManagerCommand;
use SecretSanta\Command\SecretSantaGeneratorCommand;

$loader = new UniversalClassLoader();

// register classes with namespaces
$loader->registerNamespaces(array(
    'Symfony\Component'	=> BASE_DIR . '/src/vendor',
    'SecretSanta'			=> BASE_DIR . '/src',
));

// activate the autoloader
$loader->register();

$app = new Application();
$app->add(new SecretSantaManagerCommand());
$app->add(new SecretSantaGeneratorCommand());
$app->run();