#!/usr/bin/env php
<?php

define('BASE_DIR', __DIR__);

require_once BASE_DIR . '/src/vendor/Symfony/Component/ClassLoader/UniversalClassLoader.php';

use Symfony\Component\ClassLoader\UniversalClassLoader;
use Symfony\Component\Console\Application;

use SecretSanta\Command\SecretSantaManagerCommand;
use SecretSanta\Command\SecretSantaGeneratorCommand;

$loader = new UniversalClassLoader();

// register classes with namespaces
$loader->registerNamespaces(array(
    'Symfony\Component'	=> BASE_DIR . '/src/vendor',
    'SecretSanta'			=> BASE_DIR . '/src',
));

// activate the autoloader
$loader->register();

$app = new Application();
$app->add(new SecretSantaManagerCommand());
$app->add(new SecretSantaGeneratorCommand());
$app->run();